### PR TITLE
Added icon for window

### PR DESCRIPTION
**Pull request by ryanlarkin**
Still didn't un-obfuscate it though.

### CODE REVIEW

**Comment by ryanlarkin** [comment]
No7

**Comment by ryanlarkin** [comment]
Stop don't merge

**Comment by ryanlarkin** [comment]
Yet

**Comment by ryanlarkin** [comment]
Nevermind you can merge it

**Comment by ghost** [comment]
Ok, I'll still check it over though

**Comment by ryanlarkin** [comment]
wait don't merge

**Comment by ryanlarkin** [comment]
ok it's ok now

**Comment by ryanlarkin** [comment]
Yay.

**Pull request merged**
